name: Build and Deploy Botasaurus Desktop API Docs

on:
  push:
    branches: [ master ]
    # paths:
    #   - 'js/botasaurus-desktop-api/botasaurus-desktop-api-docs/**'

jobs:
  build-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed for git diff and push later

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'


    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0             # otherwise, you will fail to push refs to dest repo

    - name: Install dependencies and build
      working-directory: js/botasaurus-server-js
      run: |
        npm i --legacy-peer-deps
        npm publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    # - uses: JS-DevTools/npm-publish@v3
    #   with:
    #     token: ${{ secrets.NPM_TOKEN }}
