name: Build and Deploy Botasaurus Desktop API Docs

on:
  push:
    branches: [ master ]
    # paths:
    #   - 'js/botasaurus-desktop-api/botasaurus-desktop-api-docs/**'

jobs:
  build-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Needed for git diff and push later

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0             # otherwise, you will fail to push refs to dest repo

    - uses: shallwefootball/s3-upload-action@master
      
      with:
        aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        source_dir: './js/botasaurus-desktop-api/botasaurus-desktop-api-docs/src'
